Clarify usage in Readme
twitter-together/action pull request #213
Opened 2022-10-01 01:35 UTC by IstoraMandiri

To help avoid confusion about usage re: #209

2022-10-01 01:44 UTC, MattIPv4 commented
@gr2m Thoughts here? I don't particularly see the need to state requiring a new repo here, the action would work in any repo assuming the tweets directory is present (e.g. a general repo dedicated to everything social-related for a project).

2022-10-02 00:48 UTC, IstoraMandiri commented
Fair comment, I've updated the wording. How is this?

2022-10-02 00:50 UTC, MattIPv4 requested changes
Some copy tweaks

2022-10-02 00:50 UTC, MattIPv4 commented on README.md
> +Unless you wish to contribute to this project, you don't need to fork this repository. Instead, complete the following steps within your own new or existing GitHub respositry.
```suggestion
Unless you wish to contribute to this project, you don't need to fork this repository. Instead, you can make use of this GitHub Action from the comfort of your own repository (either a new one, or one you already have) by creating a GitHub Actions workflow following these steps:
```

2022-10-02 01:00 UTC, IstoraMandiri commented on README.md
> +Unless you wish to contribute to this project, you don't need to fork this repository. Instead, complete the following steps within your own new or existing GitHub respositry.
Very good!

2022-10-02 15:11 UTC, MattIPv4 approved these changes
LGTM

2022-10-03 22:13 UTC, gr2m approved these changes
Thanks a lot!

2022-10-03 22:14 UTC, merged

2022-10-03 22:27 UTC, gr2m commented
:tada: This PR is included in version 2.1.3 :tada:

The release is available on [GitHub release](https://github.com/twitter-together/action/releases/tag/v2.1.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: